- README.md
- wiki.py
Currently, the data path is fixed to the wiki folder. This change enables wikmd to use an arbitrary path set via environment variable WIKI_DATA as data path.
> Make the data path configurable via env var WIKI_DATA

- README.md
- wiki.py
Feel free to deny the merge if you want! This was an option I wanted and thought it may be good to submit a PR.
Added option to change the homepage file and title of that file with an environment variable. If none is set, it'll default back to the original settings `homepage.md` and `homepage` for the title.
> Add HOMEPAGE and HOMEPAGE_TITLE environment vars

- .github/workflows/docker.yml
- docker/Dockerfile
- docker/Dockerfile.aarch64
- docker/Dockerfile.armhf
- docker/README.md
- docker/root/etc/cont-init.d/30-config
- docker/root/etc/services.d/wikmd/run
Fixing the Docker images and add a docker CI workflow.
- Changed context of the Dockerfiles so that they build from the local sources rather than from an artifact pulled from GitHub. This allows to build/publish images at different tags from the CI (e.g. `linbreux/wikmd:v1`, `linbreux/wikmd:1.2`, `linbreux/wikmd:main`, `linbreux/wikmd:pr-3` etc).
- Fixed the environment variable that changed `WIKI_DATA` -> `WIKI_DIRECTORY`
- The docker image does not change the permission of bind mounted volume anymore.
- Populate bind mounted volume with the examples if it is empty
- Update documentation
- Add a docker CI workflow
- Build docker image
- Test docker image
- Publish docker image
The 'publish' part of the CI workflow is disabled for now. 
~~- [ ] In case of new feature, add short overview …
> Fix docker image + CI

- .github/workflows/docker.yml
Fix the docker image tagging in CI.
Currently wikmd is not following the [semver](https://semver.org/) standard for git tags. This causes the [`metadata-action`](https://github.com/docker/metadata-action) to [silently fail](https://github.com/docker/metadata-action/issues/200) and an empty docker tag is generated. This empty tag is passed on all the way down to `docker run` which then fails.
With this change, the CI will create docker tags base on,
- pr number e.g. `linbreux/wikmd:pr-5`
- git tag e.g. `linbreux/wikmd:v1.6`
- `main` branch -> `linbreux/wikmd:edge`
> fix docker image tagging

- .github/workflows/docker.yml
Fix docker CI.
Test for each docker tag created.
> fix docker ci

- config.py
- docs/environment variables.md
- docs/yaml-configuration.md
- requirements.txt
- templates/base.html
- templates/knowledge-graph.html
- templates/new.html
- web_dependencies.py
- wiki.py
- wikmd-config.yaml
This pull request adds the local_mode. When in local_mode no external CDNs get used as requested in #50.
I added local_mode to `config.py`. If `cfg.local_mode` is `True` the web dependencies get downloaded, if they aren't already on disk. For this I added `requests` to the `requirements.txt`. The templates now use the `system.web_deps` dictionary to get the correct web path for the dependencies.
> add local mode

- docs/installation/regular_install.md
Added a part in the install process on how to fix `Python.h is missing` error upon pip install by installing python3-dev.
Added a part in the install process on how to fix `gcc python3-dev is missing` error upon pip install.
Fixed one typo.
When i installed this, i encountered an issue when doing pip install requirements that would fail to build psutils, claiming Python.h was missing. took me a couple minutes to figure out how to fix it by installing python3-dev.
Decided to add back to the docs in hopes that it saves someone else some time.
I am unsure how common this issue is? i experienced this installing on both Fedora 36 and Ubuntu Server 20.04.
Also added a missing `h` letter. (te -> the)
> Add solutions for potentially obscure install issue

- docs/installation/regular_install.md
As i was installing this as a service on Ubuntu service 20.04.5 LTS, i came across three issues:
1. `/venv/` in service file was incorrectly written as `/env/`
2. user was predefined as `brecht`, which would cause the service to fail as user did not exist (may vary by machine)
3. service was unable to access installed python dependencies from the virtual environment and user space- and required installing from superuser
1. renamed `/env/` to `/venv/`
2. user entry was changed to `<user>` for the end user to change
3. added instructions on how to install requirements system-wide should the service not be able to access the virtual environment installed requirements
> Added solution for missing python deps when running as service

- cache.py
Create a fresh new cache each time wikmd is started/restarted
This will fix an issue where creating a cache with a newer version of Python and then running wikmd again with an old version of Python would cause a `pickle` failure.
> Create a fresh new cache each time wikmd is started/restarted

- git_manager.py
- search.py
- tests/test_search.py
A fix for abs path issues and documenting moving events.
Fixes:
* Rel paths causing abs paths to break when indexing documents
* git_manager bug added in the search feature that is a result of me not correctly removing the git_manager alterations when searchindex was moved from the wiki content directory
Adds:
* Ability for indexing moved documents. Without this change documents that are moved remain in the search index until a fresh index is created. This fixes that and correctly calls a delete() on the old path and index() on the new path.
> Fixes/changes for #65

- docker/Dockerfile.aarch64
- docker/Dockerfile.armhf
The Arm docker images no longer built due to the lxml dependency.
I `apt install libxml2-dev libxslt1-dev` as required by the lxml package. I don't know why this isn't needed for x86_64.
- builds and works on armhf
- builds on aarch64, haven't actually run it
> fix the armhf and aarch64 Docker images

- wiki.py
Title
From the [python docs](https://docs.python.org/3/library/random.html):
> Warning
The pseudo-random generators of [the random] module should not be used for security purposes. For security or cryptographic uses, see the secrets module.
> Use secrets instead of random for generating session tokens

- wiki.py
Remove the search term escaping to improve search functionality. 
This will allow search to now correctly split terms, as well as allow using + to force AND in the search query.
i.e. `hi+hello` means `AND(Term(Hi), Term(Hello))`
By default a space means OR, i.e. `hi hello` means `OR(Term(hi), Term(hello))`
> Remove the search term escaping to improve search functionality. 

- search.py
- templates/search.html
- tests/test_search.py
- wiki.py
Add pagination to search results
Adds pagination to search results rather than only display the top 10 results.
Here are a couple of screenshots of how it'll look in light mode and dark mode. _Please note that to easily test pagination here I simply copied the `Features.md` document 20 times and changed the filename, hence all the results are for `features`._
If there is only one page of search results, the pagination is not displayed
> Add pagination to search results

- docs/Using the wiki.md
- docs/environment variables.md
- docs/installation/regular_install.md
- knowledge_graph.py
- search.py
- templates/knowledge-graph.html
- templates/list_files.html
- templates/new.html
- templates/search.html
- tests/test_basics.py
- utils.py
- wiki.py
- wiki/How to use the wiki.md
- wiki/homepage.md
Fixed some typos and fixed some issues with the code / made it more readable.
- use os.path.join and f-strings instead of concatenating strings
- remove unneeded imports
- create the upload folder if it does not exist
- remove unneeded statements in knowledge-graph.html
- make list_files.html more readable
- close a tags in list_files.html and search.html
- new.html
- use navigator.clipboard.writeText instead of document.execCommand since it is deprecated
- create the message texts more idiomatically
> Small code improvements

- templates/base.html
- wiki.py
Change dark mode toggle to use a return path as a request argument rather than using the Referer header.
Fixes #76
Really simple change, it'll add a return path to the `toggle-darktheme` route as a query string, if one isn't provided it will default to directing the user to `/` after toggling.
> Change dark mode toggle to use a return path as a request argument rather than using the Referer header. Fixes #76

- docker/Dockerfile
- docker/Dockerfile.aarch64
- docker/Dockerfile.armhf
This fixes the CI failing. Jammy has a more recent version of python.
> docker bionic to jammy

- wiki.py
Instead of showing a traceback error page, we can do something more useful: prompt a user to create a new page if it does not exist! Bonus: by using `?page=` url parameter we can specify which page we are going to edit. See the example below.
Before displaying a page, wikmd checks mtime of a file. If a file does not exist, it will throw a FileNotFound error. We can catch this error and do a redirect instead. More to that, we can pass a page name as an argument to the `/add_new` route and therefore put the path to a page right into a template.
> Godlike editing speed: redirecting to /add_new if page does not exist

- git_manager.py
- wiki.py
Adds a sync back from a git repo.
On page loads it performs a `git pull` in the background. 
- ~~[ ] In case of new feature, add short overview in ```docs/<corresponding file>```~~ N/A
- ~~[ ] Tested changes~~ N/A
- Tested by:
1. Making a change in the Web UI 
2. Confirm that the change is in Github repo
3. Edit a file in Github repo 
4. Refresh and see the change in Web UI 
**Note: Between steps 3 and 4 you may nee to allow for a second or two for changes to propagate depending on network**
> adds a git pull on page featch

- static/css/wiki.dark.css
Change the color of form controls to be darker, which is more inline with how fields like that are usually handled.
> fix: changed form-control to be darker in darkmode.

- plugins/alerts/alerts.py
This is required on newer version of python and shouldn't change the regexp outcome.
> fix: move regexp into the start of the pattern

- wiki.py
Fixes the `lxml.etree.ParserError` error you get when you try to create an empty page or edit an page by deleting all text you will get an error
> fix:do not attempt to clean html if it's empty

- templates/new.html
Give the user a warning when they try to navigate away with changes within the  `content`.
It would be nice to include the title too somehow, but couldn't come up with a neat solution for it. At least this will make sure people don't lose their content.
> feat: basic implementation to check if edit pages have modified content

- wiki.py
Ensure the name of a page is secure.
* Checks if a page name is secure through `werkzeug.utils.secure_filename`.
* Checks that the page name isn't empty.
Closes https://github.com/Linbreux/wikmd/issues/140
> feat: added checks to ensure the page can be created

- wiki.py
Clean up any empty directory automatically.
Closes https://github.com/Linbreux/wikmd/issues/142
> feat: remove a folder if it's empty

- config.py
Use the default value if the value is missing from the yml file.
This seemed to be the intent but cause of the hash look up if the key was missing it failed. 
With .get we can easily provide a default value.
> fix: use default value if it isn't defined in the yaml file

- src/wikmd/utils.py
- src/wikmd/wiki.py
- tests/test_basics.py
At one point I accidentally removed to much validation
Also adds tests to make sure it doesn't break again
> fix: allowed and disallowed file names

- src/wikmd/templates/base.html
- src/wikmd/templates/search.html
- src/wikmd/wiki.py
- tests/test_basics.py
It's conventional to use a uri for searching
It also makes the code cleaner as it do not have to guard against a search everywhere.
_Technically_ a breaking change as someone _could_ have saved a search as a bookmark, or done other things that assumes the search location. However, I don't think that's worth taking into consideration.
> fix: use uri for search

- src/wikmd/config.py
- src/wikmd/plugins/draw/draw.py
- src/wikmd/wiki.py
- tests/test_basics.py
Add drawings to wiki folder. This allows them to be in git.
See issue #150
> Missing drawings from git

- src/wikmd/web_dependencies.py
Polyfill.io doesn't have the best reputation these days. I've changed the source of the script to cloudflare.
- https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk
- https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet
The only test I've done is starting a container with LOCAL_MODE true and false. Can do additional tests but I'll need some pointers :)
> Get polyfill.js from cloudflare

- src/wikmd/web_dependencies.py
Download bootstrap-icons font files when in LOCAL_MODE and create relative parent folders for files if necessary.
In this case it creates **static/css/fonts/**. Not the best since there already is a fonts folder in static, but it doesn't match the path in bootstrap-icons.css. There are of course other solutions to this problem.
> Download bootstrap-icons fonts in local_mode

- src/wikmd/static/css/wiki.css
Hi! This just adds a bit of margin to footnote backlinks :)
before:
after:
> added margin to footnote backlinks

- docs/environment variables.md
- docs/yaml-configuration.md
- src/wikmd/config.py
- src/wikmd/templates/base.html
- src/wikmd/wiki.py
- src/wikmd/wikmd-config.yaml
Changes from hardcoded "Wiki" as title in head and navbar to a variable.
It would be cool to have a prefix in **<title>** depending on which page is displayed. E.g. "homepage | Wiki".  I could have a look at figuring it out but I'm not sure what would be a clean way to implement it.
- Adds variable WIKI_TITLE.
- Defaults to "Wiki".
- Passes it in all render_template() calls.
> Wiki title as variable
